import initSqlJs from "sql.js";
import { Deck, Note, Notetype, Package } from "ankipack";
import type { AnkiNote } from "@/app/utils/ankiSchema";

export const GOOSEBERRY_NOTE_TYPE_ID = 1760000000001;
export const GOOSEBERRY_NOTE_TYPE_NAME = "Gooseberry Vocabulary v1";

export const GOOSEBERRY_FIELD_NAMES = [
  "Gooseberry ID",
  "Original",
  "Translation",
  "Word Forms",
  "Sample",
  "Sample Translation",
  "Comments",
  "Source Language",
  "Target Language",
  "Source Audio",
] as const;

export interface AnkiMediaFile {
  filename: string;
  data: Uint8Array;
}

const CARD_CSS = `
.card {
  box-sizing: border-box;
  max-width: 760px;
  margin: 0 auto;
  padding: 24px;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  font-size: clamp(20px, 4vw, 32px);
  line-height: 1.35;
  text-align: center;
  color: #172033;
  background: #ffffff;
}

.direction {
  margin-bottom: 18px;
  color: #64748b;
  font-size: 0.55em;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

.prompt,
.answer {
  font-weight: 650;
}

.forms {
  margin-top: 24px;
  color: #334155;
}

.example {
  margin-top: 28px;
  text-align: left;
}

.example-source {
  font-style: italic;
}

.example-translation {
  margin-top: 8px;
  font-weight: 600;
}

.comments {
  margin-top: 28px;
  padding-top: 18px;
  border-top: 1px solid #cbd5e1;
  color: #475569;
  font-size: 0.65em;
  text-align: left;
}

#typeans {
  box-sizing: border-box;
  width: min(100%, 560px);
  margin-top: 24px;
  padding: 10px 12px;
  font: inherit;
}

hr#answer {
  margin: 28px 0;
  border: 0;
  border-top: 1px solid #94a3b8;
}

.card.nightMode,
.card.night_mode,
.nightMode .card,
.night_mode .card {
  color: #e2e8f0;
  background: #0f172a;
}

.nightMode .direction,
.night_mode .direction,
.nightMode .comments,
.night_mode .comments {
  color: #94a3b8;
}

.nightMode .forms,
.night_mode .forms {
  color: #cbd5e1;
}
`;

const DETAILS = `
{{#Word Forms}}<div class="forms">{{Word Forms}}</div>{{/Word Forms}}
{{#Sample}}<div class="example"><div class="example-source">{{Sample}}</div>{{#Sample Translation}}<div class="example-translation">{{Sample Translation}}</div>{{/Sample Translation}}</div>{{/Sample}}
{{#Comments}}<div class="comments">{{Comments}}</div>{{/Comments}}
`;

export function createGooseberryNotetype(): Notetype {
  return new Notetype({
    id: GOOSEBERRY_NOTE_TYPE_ID,
    name: GOOSEBERRY_NOTE_TYPE_NAME,
    sortFieldIndex: 1,
    css: CARD_CSS,
    fields: GOOSEBERRY_FIELD_NAMES.map((name) => ({ name })),
    templates: [
      {
        name: "Recognition",
        questionFormat: `
<div class="direction">{{Source Language}} → {{Target Language}}</div>
<div class="prompt">{{Original}}</div>
{{Source Audio}}
`,
        answerFormat: `
{{FrontSide}}
<hr id="answer">
<div class="answer">{{Translation}}</div>
${DETAILS}
`,
      },
      {
        name: "Production",
        questionFormat: `
<div class="direction">{{Target Language}} → {{Source Language}}</div>
<div class="prompt">{{Translation}}</div>
`,
        answerFormat: `
{{FrontSide}}
<hr id="answer">
<div class="answer">{{Original}}</div>
{{Source Audio}}
${DETAILS}
`,
      },
      {
        name: "Word Forms",
        questionFormat: `
{{#Word Forms}}
<div class="direction">Word forms</div>
<div class="prompt">{{Original}}</div>
{{Source Audio}}
<div class="forms">{{Translation}}</div>
{{/Word Forms}}
`,
        answerFormat: `
{{FrontSide}}
<hr id="answer">
<div class="answer">{{Word Forms}}</div>
{{#Sample}}<div class="example"><div class="example-source">{{Sample}}</div>{{#Sample Translation}}<div class="example-translation">{{Sample Translation}}</div>{{/Sample Translation}}</div>{{/Sample}}
{{#Comments}}<div class="comments">{{Comments}}</div>{{/Comments}}
`,
      },
      {
        name: "Example",
        questionFormat: `
{{#Sample}}{{#Sample Translation}}
<div class="direction">Example</div>
<div class="forms">{{Translation}}</div>
<div class="prompt example">{{Sample Translation}}</div>
{{/Sample Translation}}{{/Sample}}
`,
        answerFormat: `
{{FrontSide}}
<hr id="answer">
<div class="answer">{{Original}}</div>
{{Source Audio}}
<div class="example example-source">{{Sample}}</div>
{{#Comments}}<div class="comments">{{Comments}}</div>{{/Comments}}
`,
      },
      {
        name: "Type Answer",
        questionFormat: `
<div class="direction">Type {{Source Language}}</div>
<div class="prompt">{{Translation}}</div>
{{type:Original}}
`,
        answerFormat: `
{{FrontSide}}
<hr id="answer">
{{type:Original}}
{{Source Audio}}
${DETAILS}
`,
      },
    ],
  });
}

export function buildAnkiPackage(
  deckName: string,
  notes: AnkiNote[],
  sourceLang: string,
  targetLang: string,
  media: AnkiMediaFile[] = [],
): Package {
  const notetype = createGooseberryNotetype();
  const deck = new Deck({
    name: deckName,
    description:
      "Vocabulary cards generated by Gooseberry. Each note creates related recognition, production, grammar, example, and typed-answer cards.",
    config: null,
  });

  for (const note of notes) {
    deck.addNote(
      new Note({
        notetype,
        guid: note.guid,
        tags: parseTags(note.tags),
        fields: [
          escapeField(note.sourceId || note.guid),
          escapeField(note.original),
          escapeField(note.translation),
          escapeField(note.wordForms),
          escapeField(note.sample),
          escapeField(note.sampleTranslation),
          escapeField(note.comments),
          escapeField(sourceLang),
          escapeField(targetLang),
          note.sourceAudio ? `[sound:${note.sourceAudio}]` : "",
        ],
      }),
    );
  }

  const pkg = new Package();
  pkg.addDeck(deck);
  for (const file of media) {
    pkg.addMedia(file.filename, file.data);
  }
  return pkg;
}

export async function createApkgPackage(
  deckName: string,
  notes: AnkiNote[],
  sourceLang: string,
  targetLang: string,
  media: AnkiMediaFile[] = [],
): Promise<Buffer> {
  const SQL = await initSqlJs();
  const bytes = await buildAnkiPackage(
    deckName,
    notes,
    sourceLang,
    targetLang,
    media,
  ).toUint8Array(SQL);

  return Buffer.from(bytes);
}

function parseTags(tags: string): string[] {
  return [
    ...new Set(
      tags
        .split(/\s+/)
        .map((tag) => tag.trim())
        .filter(Boolean),
    ),
  ];
}

function escapeField(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;")
    .replaceAll("\r\n", "<br>")
    .replaceAll("\n", "<br>")
    .replaceAll("\r", "<br>");
}
